
/****************************************************************************
**
** Copyright (C) 2017 The Qt Company Ltd.
** Contact: https://www.qt.io/licensing/
**
** This file is part of Qt 3D Studio.
**
** $QT_BEGIN_LICENSE:GPL-EXCEPT$
** Commercial License Usage
** Licensees holding valid commercial Qt licenses may use this file in
** accordance with the commercial license agreement provided with the
** Software or, alternatively, in accordance with the terms contained in
** a written agreement between you and The Qt Company. For licensing terms
** and conditions see https://www.qt.io/terms-conditions. For further
** information use the contact form at https://www.qt.io/contact-us.
**
** GNU General Public License Usage
** Alternatively, this file may be used under the terms of the GNU
** General Public License version 3 as published by the Free Software
** Foundation with exceptions as appearing in the file LICENSE.GPL3-EXCEPT
** included in the packaging of this file. Please review the following
** information to ensure the GNU General Public License requirements will
** be met: https://www.gnu.org/licenses/gpl-3.0.html.
**
** $QT_END_LICENSE$
**
****************************************************************************/
//===============================================================================================================================
//	CODEGEN -- FILE CREATED BY STUDIO CODE GENERATION SYSTEM
//
//	Do not modify the contents of this file.  Your changes will be destroyed by
//	code generation.
//
//	Please see the CodeGen folder for more information or to make changes.
//  StringsReadme.htm
//===============================================================================================================================
//{{AFX_INSERT_LOCATION}}

#ifndef STUDIOSTRINGSH
#define STUDIOSTRINGSH

#define STRING_RESOURCE_COUNT 254
#define IDS_PREFS_PRESENTATIONWIDTH 1
#define IDS_PREFS_PRESENTATIONHEIGHT 2
#define IDS_PREFS_PRESENTATIONASPECTRATIO 3
#define IDS_PREFS_AUTHORNAME 4
#define IDS_PREFS_COMPANYNAME 5
#define IDS_PREFS_NUDGEAMOUNT 6
#define IDS_PREFS_SNAPRANGE 7
#define IDS_PREFS_INTERPOLATIONDEFAULT 8
#define IDS_PREFS_TIMELINEGRIDSNAPPING 9
#define IDS_PREFS_TIMELINEGRIDRESOLUTION 10
#define IDS_PREFS_RESTOREDEFAULTS 11
#define IDS_PREFS_REFERENCECONTROLS 12
#define IDS_WEBSITELINK 13
#define IDS_SUPPORTEMAIL_TEXT 14
#define IDS_SUPPORTEMAIL 15
#define IDS_PALETTE_TIMELINE 16
#define IDS_PALETTE_INSPECTOR 17
#define IDS_PALETTE_SLIDE 18
#define IDS_PALETTE_ACTION 19
#define IDS_PALETTE_BASIC_OBJECTS 20
#define IDS_PALETTE_PROJECT 21
#define IDS_OBJTYPE_MASTER 22
#define IDS_SLIDE_EDIT_MASTER 23
#define IDS_SLIDE_LEAVE_MASTER 24
#define IDS_SLIDE_DEFAULT_TITLE 25
#define IDS_HELP_FILE_NAME 26
#define IDS_PREF_RESTOREDEFAULT_TITLE 27
#define IDS_PREF_RESTOREDEFAULT_TEXT 28
#define IDS_PREF_INTERPOLATION_1 29
#define IDS_PREF_INTERPOLATION_2 30
#define IDS_PREF_SNAPRANGE_1 31
#define IDS_PREF_SNAPRANGE_2 32
#define IDS_PREF_SNAPRANGE_3 33
#define IDS_ERROR_REFRESHRESOURCETEXT 34
#define IDS_ERROR_REFRESHRESOURCETITLE 35
#define IDS_ERROR_IMPORTRESOURCETEXT 36
#define IDS_ERROR_IMPORTRESOURCETEXT_CHECKFILE 37
#define IDS_ERROR_IMPORTRESOURCETEXT_REASON 38
#define IDS_ERROR_IMPORTRESOURCETEXT_COMPLETEWITHWARNING 39
#define IDS_ERROR_IMPORTRESOURCETEXT_FAILED 40
#define IDS_ERROR_IMPORTRESOURCETITLE 41
#define IDS_ERROR_IMPORTRESOURCETITLE_ERROR 42
#define IDS_ERROR_IMPORTRESOURCETITLE_WARNING 43
#define IDS_ERROR_IMPORTLUARESOURCETEXT 44
#define IDS_ERROR_LOADPRESENTATION 45
#define IDS_ERROR_LOADFILENOTEXIST 46
#define IDS_ERROR_LOADPRESENTATION_TITLE 47
#define IDS_ERROR_EXPORTPRESENTATION 48
#define IDS_ERROR_MISSING_RESOURCES 49
#define IDS_ERROR_IMPORTUNSUPPORTEDRESOURCETYPETEXT 50
#define IDS_ERROR_MSGTITLE 51
#define IDS_ERROR_CLIENTSAVE 52
#define IDS_ERROR_PROJECT_VARIABLES_TITLE 53
#define IDS_ERROR_PROJECT_VARIABLES_MSG 54
#define IDS_ERROR_OBJECT_RENAME_TITLE 55
#define IDS_ERROR_OBJECT_RENAME_EMPTY_STRING 56
#define IDS_ERROR_OBJECT_RENAME_DUPLICATED_STRING 57
#define IDS_ERROR_PATHOLOGICAL_PASTE_TITLE 58
#define IDS_ERROR_PATHOLOGICAL_PASTE_MESSAGE 59
#define IDS_ERROR_MSGPASSING 60
#define IDS_WARNING_IMPORTLUARESOURCETEXT 61
#define IDS_WARNING_MSGTITLE 62
#define IDS_TITLE_WARNING 63
#define IDS_FILE_DESC_UIP 64
#define IDS_FILE_EXT_UIP 65
#define IDS_LIBRARYIMPORT_MODEL 66
#define IDS_LIBRARYIMPORT_IMAGE 67
#define IDS_LIBRARYIMPORT_BEHAVIOR 68
#define IDS_LIBRARYIMPORT_MESH 69
#define IDS_LIBRARYIMPORT_IMPORT 70
#define IDS_LIBRARYIMPORT_EFFECT 71
#define IDS_PROJNAME 72
#define IDS_REPORTDLG_INFO 73
#define IDS_REPORTDLG_DESCHEADER 74
#define IDS_REPORTDLG_EMAILHEADER 75
#define IDS_REPORTDLG_SYSINFOHEADER 76
#define IDS_COMMAND_COPYACTION 77
#define IDS_COMMAND_PASTEACTION 78
#define IDS_COMMAND_CUTACTION 79
#define IDS_COMMAND_DELETEACTION 80
#define IDS_HELP_BEHAVIORREFERENCE 81
#define IDS_SAVE_READONLY_WARNING 82
#define IDS_COMMENT_SUGGESTION_TOADDR 83
#define IDS_COMMENT_BUG_TOADDR 84
#define IDS_COMMENT_TYPE_SUGGESTION 85
#define IDS_COMMENT_TYPE_BUG 86
#define IDS_CM_RENAME_OBJECT 87
#define IDS_CM_DUPLICATE_OBJECT 88
#define IDS_CM_DELETE_OBJECT 89
#define IDS_CM_MAKE_COMPONENT 90
#define IDS_CM_COPY_OBJECT_PATH 91
#define IDS_CM_EXTERNALIZE_OBJECT_BUFFER 92
#define IDS_CM_INTERNALIZE_OBJECT_BUFFER 93
#define IDS_CM_INSPECT_COMPONENT 94
#define IDS_TEXTEDIT_CONTEXT_MENU_CUT 95
#define IDS_TEXTEDIT_CONTEXT_MENU_COPY 96
#define IDS_TEXTEDIT_CONTEXT_MENU_PASTE 97
#define IDS_UIC_STUDIO_VERSION 98
#define IDS_CRASH_REPORT_TOADDR 99
#define IDS_CRASH_REPORT_FROMADDR 100
#define IDS_CRASH_REPORT_SERVERADDR 101
#define IDS_UICOMPOSER_PALETTE_SETTINGS_REGISTRY_KEY 102
#define IDS_COPYPASTE_FORMAT_NAME 103
#define IDS_STUDIOFONT_SIZE 104
#define IDS_STUDIOPREFSTITLE 105
#define IDS_NOOBJECTSELECTED 106
#define IDS_CONTEXTKEY_SETINTERPOLATION 107
#define IDS_CONTEXTKEY_DELETESELECTED 108
#define IDS_CONTEXTKEY_CUTSELECTED 109
#define IDS_CONTEXTKEY_COPYSELECTED 110
#define IDS_CONTEXTKEY_PASTE 111
#define IDS_CONTEXTKEY_INSERTKEY 112
#define IDS_CONTEXTKEY_SETKEYFRAMETIME 113
#define IDS_CONTEXTKEY_DELETECHANNEL 114
#define IDS_CONTEXTKEY_BARCOLOR 115
#define IDS_CONTEXTKEY_BARTEXT 116
#define IDS_CONTEXTKEY_SHOWTIMEBARHANDLES 117
#define IDS_CONTEXTKEY_HIDETIMEBARHANDLES 118
#define IDS_CONTEXTKEY_SETTIMEBARTIME 119
#define IDS_CONTEXTKEY_MAKE_ANIMATION_DYNAMIC 120
#define IDS_CONTEXTKEY_MAKE_ANIMATION_STATIC 121
#define IDS_CONTEXTKEY_MAKE_ANIMATIONS_DYNAMIC 122
#define IDS_CONTEXTKEY_MAKE_ANIMATIONS_STATIC 123
#define IDS_CONTEXT_SLIDE_NEW 124
#define IDS_CONTEXT_SLIDE_DELETE 125
#define IDS_CONTEXT_SLIDE_DUPLICATE 126
#define IDS_CONTEXT_LINK_STATEWISE 127
#define IDS_CONTEXT_UNLINK_STATEWISE 128
#define IDS_HK_CMD 129
#define IDS_HK_ALPHALOCK 130
#define IDS_CONTROLS_FLOAT_MINUS 131
#define IDS_CONTROLS_FLOAT_PERIOD 132
#define IDS_PROJECT_BEHAVIORLIB_PATH 133
#define IDS_PROJECT_EFFECTLIB_PATH 134
#define IDS_PROJECT_FONTLIB_PATH 135
#define IDS_PROJECT_IMAGELIB_PATH 136
#define IDS_PROJECT_MATERIALLIB_PATH 137
#define IDS_PROJECT_MODELLIB_PATH 138
#define IDS_PROJECT_BUTTON_BEHAVIOR 139
#define IDS_PROJECT_BUTTON_EFFECT 140
#define IDS_PROJECT_BUTTON_FONT 141
#define IDS_PROJECT_BUTTON_IMAGE 142
#define IDS_PROJECT_BUTTON_MATERIAL 143
#define IDS_PROJECT_BUTTON_MODEL 144
#define IDS_PROJECT_CM_SHOW_IN_EXPLORER 145
#define IDS_PROJECT_CM_COPY_PATH 146
#define IDS_PROJECT_CM_COPY_FULL_PATH 147
#define IDS_PROJECT_CM_LOCATE_FOLDER 148
#define IDS_PROJECT_CM_LOCATE_FILE 149
#define IDS_PROJECT_FILE_NOT_IN_DOCUMENT_SUBDIR 150
#define IDS_UNTITLED_DOCUMENT_TITLE 151
#define IDS_CREATE_NEW_DOCUMENT_TITLE 152
#define IDS_MENU_WIN_UNDO_FORMAT 153
#define IDS_MENU_WIN_REDO_FORMAT 154
#define IDS_MENU_WIN_COPY_FORMAT 155
#define IDS_MENU_WIN_PASTE_FORMAT 156
#define IDS_MENU_WIN_CUT_FORMAT 157
#define IDS_MENU_COPYPASTE_TYPE_ACTION 158
#define IDS_MENU_COPYPASTE_TYPE_KEYFRAMES 159
#define IDS_MENU_COPYPASTE_TYPE_OBJECT 160
#define IDS_PROMPT_FOR_SAVE 161
#define IDS_PROMPT_FOR_REVERT 162
#define IDS_WAIT_LOADING 163
#define IDS_HELP_VISIT_QT 164
#define IDS_FLTR_TOOLTIP_BEHAVIOR1 165
#define IDS_FLTR_TOOLTIP_BEHAVIOR2 166
#define IDS_FLTR_TOOLTIP_PROPERTIES1 167
#define IDS_FLTR_TOOLTIP_PROPERTIES2 168
#define IDS_FLTR_TOOLTIP_MATERIALS1 169
#define IDS_FLTR_TOOLTIP_MATERIALS2 170
#define IDS_FLTR_TOOLTIP_SHY1 171
#define IDS_FLTR_TOOLTIP_SHY2 172
#define IDS_FLTR_TOOLTIP_VISIBLE1 173
#define IDS_FLTR_TOOLTIP_VISIBLE2 174
#define IDS_FLTR_TOOLTIP_LOCK1 175
#define IDS_FLTR_TOOLTIP_LOCK2 176
#define IDS_TOOLTIP_ANIMATE_TOGGLE 177
#define IDS_TIME_EDIT_DLG_GO_TO_TIME 178
#define IDS_TIME_EDIT_DLG_SET_KEYFRAME_TIME 179
#define IDS_TIME_EDIT_DLG_SET_TIMEBAR_TIME 180
#define IDS_TIME_EDIT_DLG_START_TIME 181
#define IDS_TIME_EDIT_DLG_END_TIME 182
#define IDS_TIME_EDIT_DLG_MIN_SEC_MSEC 183
#define IDS_REFRESH_IMPORT 184
#define IDS_COLORCHOOSER_AUTO 185
#define IDS_COLORCHOOSER_MORE 186
#define IDS_SPLASH_COPYRIGHT1 187
#define IDS_SPLASH_COPYRIGHT2 188
#define IDS_ABOUT_COPYRIGHT 189
#define IDS_ABOUT_FBX_CREDIT 191
#define IDS_DEFAULT_PALETTE_LAYOUT 192
#define IDS_BASIC_OBJ_PALETTE_LAYER 193
#define IDS_BASIC_OBJ_PALETTE_CAMERA 194
#define IDS_BASIC_OBJ_PALETTE_LIGHT 195
#define IDS_BASIC_OBJ_PALETTE_GROUP 196
#define IDS_BASIC_OBJ_PALETTE_CUBE 197
#define IDS_BASIC_OBJ_PALETTE_CYLINDER 198
#define IDS_BASIC_OBJ_PALETTE_CONE 199
#define IDS_BASIC_OBJ_PALETTE_RECTANGLE 200
#define IDS_BASIC_OBJ_PALETTE_SPHERE 201
#define IDS_BASIC_OBJ_PALETTE_TEXT 202
#define IDS_BASIC_OBJ_PALETTE_COMPONENT 203
#define IDS_BASIC_OBJ_PALETTE_ALIAS 204
#define IDS_CREATE_NEW_PALETTE 205
#define IDS_MOVE_PALETTE 206
#define IDS_GROUP_EXPAND_TOGGLE_TOOLTIP 207
#define IDS_GROUP_MOVE_UP_TOOLTIP 208
#define IDS_GROUP_MOVE_DOWN_TOOLTIP 209
#define IDS_ACTION_DELETE_TOOLTIP 210
#define IDS_HANDLER_CONTROL_NAME 211
#define IDS_EVENT_CONTROL_NAME 212
#define IDS_EVENT_TARGET_OBJ 213
#define IDS_EVENT_TRIGGER_OBJ 214
#define IDS_ACTION_LISTEN_FOR_STRING 215
#define IDS_ACTION_LISTEN_FOR_TELL_STRING 216
#define IDS_ACTION_LISTEN_TO_FOR_STRING 217
#define IDS_ACTION_LISTEN_TO_FOR_TELL_STRING 218
#define IDS_ACTION_NEW 219
#define IDS_DELETE_ACTION 220
#define IDS_PROPERTIES_BASIC 221
#define IDS_PROPERTIES_SHARED 222
#define IDS_OBJ_REF_PATH 223
#define IDS_OBJ_REF_PATH_TYPE 224
#define IDS_OBJ_REF_PATH_ABSOLUTE 225
#define IDS_OBJ_REF_PATH_RELATIVE 226
#define IDS_PROP_UNKNOWN_SOURCE 227
#define IDS_PROP_UNKNOWN_TARGET 228
#define IDS_PROP_UNKNOWN_PROP 229
#define IDS_PROP_UNKNOWN_HANDLER 230
#define IDS_ACTION_ENABLE_STATE 231
#define IDS_ASSET_NAME_UNKNOWN 232
#define IDS_DELETE_OBJ_CONFIRM_TITLE 233
#define IDS_DELETE_OBJ_CONFIRM_MSG 234
#define IDS_SCENE_CAMERA_VIEW 235
#define IDS_PROJECT_VARIABLES_FORMAT 236
#define IDS_CONFIG_EXPORT_PREVIEW 237
#define IDS_CONFIG_EXPORT_DEPLOY 238
#define IDS_CONFIG_PREVIEW_TITLE 239
#define IDS_CONFIG_PREVIEW_ERROR_TITLE 240
#define IDS_CONFIG_PREVIEW_ERROR_MSG 241
#define IDS_CONFIG_PREVIEW_ERROR_TEXT 242
#define IDS_CONFIG_PREVIEW_REDIRECT_ERROR 243
#define IDS_CONFIG_PREVIEW_INPUT 244
#define IDS_CONFIG_PREVIEW_OUTPUT 245
#define IDS_RENAME_OBJ_CONFIRM_TITLE 246
#define IDS_RENAME_OBJ_CONFIRM_MSG 247
#define IDS_BUILDCONFIGS_ERROR_TITLE 248
#define IDS_MISSINGSLIDE 249
#define IDS_SAVE_UNKNOWN_ERROR 250
#define IDS_GL_VERSION_ERROR 251
#define IDS_GL_VERSION_WARNING 252
#define IDS_PRESENTATION_MODIFIED_EXTERNALLY 253
#ifdef KDAB_TEMPORARILY_REMOVED
#define placeholder 254
#endif

#endif //STUDIOSTRINGSH
