isEmpty(TQTC_LICENSE_MANAGING): TQTC_LICENSE_MANAGING=$$(TQTC_LICENSE_MANAGING)
!isEmpty(TQTC_LICENSE_MANAGING) {
    include($$TQTC_LICENSE_MANAGING/studio3d/licensehandler.pri)
}

TEMPLATE = lib
TARGET = $$qtLibraryTarget(licensehandler)

DEFINES += LICENSE_HANDLER_AS_DLL LICENSE_HANDLER_EXPORTS

target.path = $$[QT_INSTALL_LIBS]
dlltarget.path = $$[QT_INSTALL_BINS]
INSTALLS += target dlltarget

DESTDIR = $$[QT_INSTALL_LIBS]
DLLDESTDIR = $$[QT_INSTALL_BINS]
